const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START", // Fetch
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS", // Fetch successful
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE", // Fetch failed
};

export default ShopActionTypes;
